const users = [
    {
      id: 1,
      nome: 'João Silva',
      email: 'joao.silva@meuguru.com',
      password: 'guru123',
      idade: 28,
      sexo: 'Masculino',
      cidade: 'Serra',
    },
    {
      id: 2,
      nome: 'Maria Souza',
      email: 'maria.souza@meuguru.com',
      password: 'guru456',
      idade: 35,
      sexo: 'Feminino',
      cidade: 'Serra',
    },
    {
      id: 3,
      nome: 'Pedro Oliveira',
      email: 'pedro.oliveira@meuguru.com',
      password: 'guru789',
      idade: 22,
      sexo: 'Masculino',
      cidade: 'Belo Horizonte',
    },
    {
      id: 4,
      nome: 'Ana Santos',
      email: 'ana.santos@meuguru.com',
      password: 'guru987',
      idade: 30,
      sexo: 'Feminino',
      cidade: 'Salvador',
    },
    {
      id: 5,
      nome: 'José Pereira',
      email: 'jose.pereira@meuguru.com',
      password: 'guru321',
      idade: 26,
      sexo: 'Masculino',
      cidade: 'Brasília',
    },
    {
      id: 6,
      nome: 'Carla Costa',
      email: 'carla.costa@meuguru.com',
      password: 'guru654',
      idade: 29,
      sexo: 'Feminino',
      cidade: 'Serra',
    },
    {
      id: 7,
      nome: 'Mário Fernandes',
      email: 'mario.fernandes@meuguru.com',
      password: 'guru987',
      idade: 32,
      sexo: 'Masculino',
      cidade: 'Porto Alegre',
    },
    {
      id: 8,
      nome: 'Fernanda Oliveira',
      email: 'fernanda.oliveira@meuguru.com',
      password: 'guru654',
      idade: 31,
      sexo: 'Feminino',
      cidade: 'Serra',
    },
    {
      id: 9,
      nome: 'Ricardo Almeida',
      email: 'ricardo.almeida@meuguru.com',
      password: 'guru321',
      idade: 27,
      sexo: 'Masculino',
      cidade: 'Fortaleza',
    },
    {
      id: 10,
      nome: 'Juliana Silva',
      email: 'juliana.silva@meuguru.com',
      password: 'guru789',
      idade: 24,
      sexo: 'Feminino',
      cidade: 'Manaus',
    },
    {
      id: 11,
      nome: 'Gabriel Santos',
      email: 'gabriel.santos@meuguru.com',
      password: 'guru123',
      idade: 33,
      sexo: 'Masculino',
      cidade: 'Belém',
    },
    {
      id: 12,
      nome: 'Larissa Costa',
      email: 'larissa.costa@meuguru.com',
      password: 'guru456',
      idade: 25,
      sexo: 'Feminino',
      cidade: 'Vitória',
    },
    {
      id: 13,
      nome: 'Daniel Oliveira',
      email: 'daniel.oliveira@meuguru.com',
      password: 'guru987',
      idade: 28,
      sexo: 'Masculino',
      cidade: 'Porto Alegre',
    },
    {
      id: 14,
      nome: 'Mariana Fernandes',
      email: 'mariana.fernandes@meuguru.com',
      password: 'guru654',
      idade: 29,
      sexo: 'Feminino',
      cidade: 'Salvador',
    },
    {
      id: 15,
      nome: 'Gustavo Pereira',
      email: 'gustavo.pereira@meuguru.com',
      password: 'guru321',
      idade: 32,
      sexo: 'Masculino',
      cidade: 'Serra',
    },
    {
      id: 16,
      nome: 'Carolina Costa',
      email: 'carolina.costa@meuguru.com',
      password: 'guru789',
      idade: 27,
      sexo: 'Feminino',
      cidade: 'Recife',
    },
    {
      id: 17,
      nome: 'Fábio Oliveira',
      email: 'fabio.oliveira@meuguru.com',
      password: 'guru654',
      idade: 34,
      sexo: 'Masculino',
      cidade: 'Curitiba',
    },
    {
      id: 18,
      nome: 'Aline Almeida',
      email: 'aline.almeida@meuguru.com',
      password: 'guru321',
      idade: 26,
      sexo: 'Feminino',
      cidade: 'Fortaleza',
    },
  ];
  
  module.exports = { users };
  